baseURL = '/'
languageCode = 'en-us'
title = "Nick Liu's Personal Website"

theme = 'ananke'

[params]
defaultTheme = "auto"
showReadingTime = true
showShareButtons = true
showPostNavLinks = true
showBreadCrumbs = true
showCodeCopyButtons = true
showWordCount = true
showRssButtonInSectionTermList = true
useHugoToc = true
disableSpecial1stPost = false
comments = false
hidemeta = false
hideSummary = false

[params.assets]
disableScrollBarStyle = false

[build]
writeStats = true

[module]
[[module.mounts]]
source = "assets"
target = "assets"

[menu]
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10

[[menu.main]]
identifier = "experience"
name = "Experience"
url = "/experience/"
weight = 20

[[menu.main]]
identifier = "education"
name = "Education"
url = "/education/"
weight = 30

[[menu.main]]
identifier = "skills"
name = "Skills"
url = "/skills/"
weight = 40

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 50

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 60
